"""English-only 365-day topic bank. Unique title + lines per day. No Malayalam."""

from __future__ import annotations

# title, scene, accent, hook, line2, line3, line4
# scene keys must exist in blender/scripts/build_topic_scene.py (unknown → labeled hero)

PRE_SCHOOL: list[tuple] = [
    ("Red Ball", "ball", "#FF5252", "Look. A red ball.", "The ball is round and red.", "Red like a strawberry.", "You found red. You did it."),
    ("Blue Ball", "ball", "#2196F3", "Look. A blue ball.", "Blue like the sky.", "The ball can roll.", "Blue. You found blue."),
    ("Yellow Sun", "sun", "#FFD54F", "Hello, yellow sun.", "The sun is bright and warm.", "Yellow like a banana.", "Warm sun. Soft day."),
    ("Green Leaf", "leaf", "#66BB6A", "A green leaf.", "Green like grass.", "The leaf is little and soft.", "Green. You found green."),
    ("Orange Cat", "cat", "#FF9800", "Hello, orange cat.", "The cat says miao, softly.", "Soft fur. Slow blink.", "Nice cat. You did it."),
    ("Purple Grape", "apple", "#AB47BC", "Purple grapes.", "Tiny round grapes.", "Purple is a fun color.", "Yum. Purple grapes."),
    ("Pink Flower", "seed", "#EC407A", "A pink flower.", "The flower is pretty.", "Pink like a cheek.", "Hello, flower."),
    ("Brown Bear", "animal", "#8D6E63", "A brown teddy bear.", "The bear is soft.", "Brown like chocolate.", "Hug the bear. Soft and safe."),
    ("White Cloud", "cloud", "#ECEFF1", "A white cloud.", "The cloud looks fluffy.", "White like milk.", "Soft cloud in the sky."),
    ("Black Night", "moon", "#455A64", "The sky is dark.", "A moon is in the night.", "Stars can twinkle.", "Quiet night. Sleepy time."),
    ("One Duck", "animal", "#FFC107", "One little duck.", "The duck says quack.", "One duck. Just one.", "You counted one."),
    ("Two Shoes", "shape", "#4FC3F7", "Two shoes.", "One. Two.", "Shoes for two feet.", "You counted two."),
    ("Three Blocks", "shape", "#FF7043", "Three blocks.", "One. Two. Three.", "Stack them up. Softly.", "You counted three."),
    ("Four Wheels", "car", "#78909C", "A bus has wheels.", "One two three four wheels.", "The bus can go.", "You counted four."),
    ("Five Fingers", "hand", "#FFCC80", "Your hand has fingers.", "One two three four five.", "Wave hello.", "You counted five."),
    ("Happy Smile", "heart", "#FF8A80", "A happy smile.", "Smile is a kind face.", "You can smile too.", "Happy. You did it."),
    ("Rain Drop", "rain", "#4FC3F7", "A rain drop.", "Drop. Drop. Drop.", "Rain is water from the sky.", "Pitter patter. Soft rain."),
    ("Big Truck", "car", "#FF7043", "A big truck.", "The truck is red.", "Vroom, slowly.", "Big truck. You saw it."),
    ("Little Ant", "ant", "#6D4C41", "A little ant.", "The ant is tiny.", "The ant walks in a line.", "Hello, tiny ant."),
    ("Soft Blanket", "shape", "#F8BBD0", "A soft blanket.", "Warm and cozy.", "Night night, blanket.", "You are safe and warm."),
    ("Circle Shape", "shape", "#29B6F6", "This is a circle.", "A circle is round.", "No corners. Just round.", "Circle. You found it."),
    ("Square Block", "shape", "#FFA726", "This is a square.", "Four sides. Same size.", "A block can be a square.", "Square. You found it."),
    ("Triangle Hat", "shape", "#66BB6A", "A triangle.", "Three sides. Pointy top.", "Like a little hat.", "Triangle. You found it."),
    ("Hop Hop", "frog", "#9CCC65", "A frog can hop.", "Hop. Hop. Hop.", "The frog is green.", "Hop like a frog."),
    ("Splash Water", "water", "#29B6F6", "Water can splash.", "Splash is wet and fun.", "Wash your hands with water.", "Splash. You did it."),
    ("Bird Tweet", "bird", "#4DB6AC", "A bird can tweet.", "Tweet tweet.", "The bird has wings.", "Hello, bird."),
    ("Fish Swim", "fish", "#26C6DA", "A fish can swim.", "Swim in the water.", "The fish has a tail.", "Swim, little fish."),
    ("Moon Glow", "moon", "#FFE082", "The moon glows.", "The moon is in the night.", "Soft yellow moon.", "Good night, moon."),
    ("Star Twinkle", "star", "#FFD54F", "A star can twinkle.", "Twinkle in the sky.", "Tiny bright star.", "You found a star."),
    ("Apple Red", "apple", "#E53935", "A red apple.", "Apples can be crunchy.", "Red apple. Yum.", "You found an apple."),
    ("Banana Yellow", "apple", "#FDD835", "A yellow banana.", "Bananas are long.", "Peel. Soft inside.", "Yellow banana. Yum."),
    ("Car Go", "car", "#42A5F5", "The car can go.", "Beep beep, softly.", "Red light stop. Green light go.", "The car goes. You watched."),
    ("Train Choo", "car", "#5C6BC0", "A train goes choo.", "The train is long.", "Wheels on the track.", "Choo choo. You heard it."),
    ("Boat Float", "wave", "#29B6F6", "A boat can float.", "The boat sits on water.", "Wave. Wave.", "Float, little boat."),
    ("Plane High", "rocket", "#90CAF9", "A plane flies high.", "Up in the sky.", "The plane has wings.", "Bye bye, plane."),
    ("Tree Tall", "tree", "#43A047", "A tall tree.", "The tree has leaves.", "Birds like trees.", "Hello, tall tree."),
    ("Seed Grow", "seed", "#A5D6A7", "A tiny seed.", "Water and sun help.", "The seed can grow.", "Grow, little seed."),
    ("Bee Buzz", "bee", "#FBC02D", "A busy bee.", "Buzz buzz, softly.", "The bee likes flowers.", "Thank you, bee."),
    ("Butterfly Soft", "seed", "#CE93D8", "A butterfly.", "Soft wings. Slow fly.", "Pretty colors.", "Bye, butterfly."),
    ("Snow Soft", "snow", "#E3F2FD", "Soft snow.", "Snow is cold and white.", "A tiny flake.", "Snow. Quiet day."),
    ("Wind Blow", "wind", "#B3E5FC", "The wind blows.", "Whoosh, softly.", "Leaves can dance.", "Feel the wind."),
    ("Hot Cocoa", "apple", "#A1887F", "Warm cocoa.", "It is not too hot.", "Sip. Cozy tummy.", "Mmm. Warm drink."),
    ("Soap Bubbles", "bubble", "#81D4FA", "Soap bubbles.", "Pop. Pop.", "Bubbles are round.", "You made a bubble."),
    ("Tooth Brush", "tooth", "#FFF8E1", "Brush your teeth.", "Brush brush brush.", "Clean teeth feel good.", "Smile. Clean teeth."),
    ("Wash Hands", "wash", "#80DEEA", "Wash your hands.", "Water and soap.", "Rub. Rinse. Dry.", "Clean hands. You did it."),
    ("Ear Listen", "ear", "#FFCCBC", "Your ears listen.", "Listen. A soft sound.", "Thank you, ears.", "You heard it."),
    ("Eye See", "eye", "#90CAF9", "Your eyes see.", "See the color. See the shape.", "Blink. Soft blink.", "You saw it."),
    ("Nose Smell", "sneeze", "#FFAB91", "Your nose can smell.", "Smell a flower. Softly.", "Sniff sniff.", "Nice smell."),
    ("Feet Walk", "hand", "#FFCC80", "Your feet can walk.", "Step. Step.", "Walk slowly.", "You walked. You did it."),
    ("Hug Care", "heart", "#F48FB1", "A gentle hug.", "Hugs can feel safe.", "Soft arms. Kind heart.", "You are loved."),
    ("Sleep Time", "moon", "#7986CB", "Sleepy time.", "Close your eyes.", "Quiet room. Soft bed.", "Good night. Sleep well."),
    ("Hello Friend", "heart", "#FF8A65", "Hello, friend.", "Wave your hand.", "Hello is a kind word.", "Hello. You said it."),
    ("Please Share", "apple", "#AED581", "Please. Thank you.", "Sharing is kind.", "One apple. Two friends.", "Kind. You did it."),
    ("Rain Boots", "rain", "#26A69A", "Rain boots.", "Splash in a puddle. Soft splash.", "Boots keep feet dry.", "Splash. Fun rain."),
    ("Umbrella Up", "rain", "#5C6BC0", "Up goes the umbrella.", "It keeps you dry.", "Pitter patter on top.", "Safe and dry."),
    ("Sand Play", "rock", "#FFCC80", "Warm sand.", "Pour. Pat. Pile.", "A little hill of sand.", "You made a pile."),
    ("Shell Find", "wave", "#80CBC4", "A sea shell.", "Hold it gently.", "The shell is curly.", "You found a shell."),
    ("Ice Cold", "ice", "#B3E5FC", "Ice is cold.", "Ice can melt.", "Cold on your finger. Softly.", "Ice. Then water."),
    ("Shadow Play", "shadow", "#78909C", "A shadow.", "Light makes a shadow.", "Wave. The shadow waves.", "Hello, shadow."),
    ("Drum Tap", "shape", "#FFB74D", "Tap a drum.", "Tap tap. Soft taps.", "You made a sound.", "Tap. You did it."),
    ("Bell Ring", "star", "#FFE082", "A little bell.", "Ring. Ring.", "The bell is bright.", "You heard the bell."),
    ("Book Time", "book", "#8D6E63", "A picture book.", "Turn the page. Gently.", "Look. A picture.", "Story time. You did it."),
    ("Crayon Draw", "shape", "#EF5350", "A crayon.", "Draw a line. Draw a dot.", "Colors on paper.", "You made a mark."),
    ("Balloon Up", "bubble", "#EF9A9A", "A balloon.", "It can float up.", "Hold the string.", "Up, balloon."),
    ("Kite Fly", "wind", "#42A5F5", "A kite in the wind.", "Hold the string.", "The kite dances.", "Fly, kite."),
    ("Puppy Soft", "animal", "#A1887F", "A soft puppy.", "The puppy wags.", "Pat gently.", "Nice puppy."),
    ("Kitten Nap", "cat", "#BCAAA4", "A kitten naps.", "Shh. Quiet.", "Soft paws. Soft purr.", "Sleepy kitten."),
    ("Bunny Hop", "animal", "#F8BBD0", "A bunny hops.", "Hop hop. Soft hop.", "Long ears.", "Hello, bunny."),
    ("Chick Peep", "egg", "#FFF59D", "A yellow chick.", "Peep peep.", "Soft feathers.", "Hello, chick."),
    ("Egg Shell", "egg", "#FFF8E1", "An egg.", "The shell is smooth.", "A chick can come later.", "Gentle egg."),
    ("Cow Moo", "animal", "#E0E0E0", "A cow says moo.", "Moo. Soft moo.", "Milk from a farm.", "Hello, cow."),
    ("Sheep Wool", "animal", "#F5F5F5", "A sheep is fluffy.", "Wool is soft.", "Baa. Soft baa.", "Hello, sheep."),
    ("Horse Clop", "animal", "#A1887F", "A horse.", "Clop clop, slowly.", "The horse is big and kind.", "Hello, horse."),
    ("Hen Peck", "egg", "#FFCC80", "A hen.", "Cluck cluck.", "Eggs in a nest.", "Hello, hen."),
    ("Owl Hoot", "bird", "#A1887F", "An owl at night.", "Hoot. Soft hoot.", "Big eyes. Quiet wings.", "Hello, owl."),
    ("Snail Slow", "animal", "#C5E1A5", "A snail is slow.", "A tiny house on its back.", "Slow is okay.", "Hello, snail."),
    ("Ladybug Dot", "ant", "#E53935", "A ladybug.", "Red with dots.", "Tiny wings.", "Hello, ladybug."),
    ("Worm Dig", "seed", "#8D6E63", "A worm in dirt.", "The worm helps the soil.", "Wiggle wiggle.", "Hello, worm."),
    ("Pond Ripple", "water", "#4DB6AC", "A pond.", "A ripple on the water.", "Frog likes the pond.", "Quiet pond."),
    ("Hill Up", "rock", "#81C784", "A little hill.", "Walk up. Walk down.", "The hill is green.", "You climbed the hill."),
    ("Bridge Over", "shape", "#90A4AE", "A bridge.", "Over the water.", "Cars can go over.", "Over the bridge."),
    ("Door Open", "shape", "#A1887F", "Open the door.", "Hello inside.", "Close the door. Gently.", "Open. Close."),
    ("Window Light", "sun", "#FFE082", "Sun in the window.", "Warm light.", "Look outside.", "Bright window."),
    ("Clock Tick", "clock", "#90CAF9", "A clock ticks.", "Tick tock. Slow tock.", "Morning. Night.", "You heard the clock."),
    ("Soap Clean", "wash", "#80DEEA", "Soap is bubbly.", "Soap helps clean.", "Rub the soap.", "Clean. You did it."),
    ("Towel Dry", "shape", "#F8BBD0", "A soft towel.", "Pat dry. Gently.", "Dry hands. Dry face.", "Dry. You did it."),
    ("Hat On", "shape", "#7E57C2", "A hat on your head.", "The hat is warm.", "Off. On.", "Hat on. You did it."),
    ("Socks Pair", "shape", "#4DB6AC", "Two socks.", "A pair. Two together.", "On your feet.", "Two socks. You did it."),
    ("Zip Coat", "shape", "#5C6BC0", "Zip the coat.", "Up. Down.", "The coat is warm.", "Zip. You did it."),
    ("Snack Time", "apple", "#FFCC80", "Snack time.", "A little bite.", "Chew slowly.", "Yum. Snack time."),
    ("Water Sip", "water", "#4FC3F7", "Sip some water.", "Water helps your body.", "Sip. Sip.", "Good water."),
    ("Thank You", "heart", "#F48FB1", "Thank you.", "Thank you is kind.", "You can say it too.", "Thank you. You said it."),
    ("Sorry Soft", "heart", "#CE93D8", "Sorry.", "Sorry is a kind word.", "We can try again.", "Sorry. Then a hug."),
    ("Wait Turn", "shape", "#9FA8DA", "Wait your turn.", "Waiting is hard. You can do it.", "Now it is your turn.", "You waited. You did it."),
    ("Quiet Please", "moon", "#B39DDB", "Quiet please.", "Soft voice.", "Quiet helps ears.", "Shh. Quiet. Good job."),
    ("Line Up", "ant", "#A5D6A7", "Line up.", "One behind one.", "Slow steps.", "You lined up."),
    ("Jump Soft", "frog", "#AED581", "A little jump.", "Bend. Jump. Land soft.", "Jumping is fun.", "You jumped."),
    ("Clap Hands", "hand", "#FFAB91", "Clap your hands.", "Clap clap.", "You made a sound.", "Clap. You did it."),
    ("Stomp Feet", "hand", "#BCAAA4", "Stomp your feet.", "Stomp. Soft stomp.", "Feel the floor.", "Stomp. You did it."),
    ("Spin Slow", "star", "#FFE082", "Spin slowly.", "Round and round. Stop.", "Dizzy? Sit down.", "Spin. Then rest."),
    ("Balance Beam", "shape", "#80CBC4", "Walk a line.", "Arms out. Slow feet.", "You can balance.", "You walked the line."),
    ("Catch Ball", "ball", "#EF5350", "Catch the ball.", "Hands ready.", "Soft catch.", "You caught it."),
    ("Roll Ball", "ball", "#42A5F5", "Roll the ball.", "Push. Roll. Stop.", "The ball is round.", "You rolled it."),
    ("Stack Cups", "shape", "#FFA726", "Stack the cups.", "Up. Up. Careful.", "A little tower.", "You stacked them."),
    ("Peek A Boo", "heart", "#F48FB1", "Peek a boo.", "Hide. Then hello.", "You are still here.", "Peek a boo. Hello."),
    ("I Love You", "heart", "#E91E63", "I love you.", "Love is a warm feeling.", "You are special.", "Love you. Always."),
]


def _pack(row: tuple) -> dict:
    title, scene, accent, *lines = row
    return {
        "title": title,
        "scene": scene,
        "accent": accent,
        "hook": lines[0],
        "narration": list(lines),
    }
